from __future__ import annotations

import html
import json
import math
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable

FAMILY_ORDER = [
    "boundary_condition_repair",
    "postprocessing_instrumentation",
    "solver_convergence_repair",
    "mesh_quality_repair",
    "source_term_calibration",
    "flow_rate_targeting",
    "pressure_drop_calibration",
    "transient_setup_repair",
    "force_coeff_instrumentation",
    "scalar_transport_repair",
    "mesh_resolution_tradeoff",
]

FAMILY_CAPTIONS = {
    "boundary_condition_repair": (
        "Animated channel fields compare an inconsistent outlet pressure condition with a repaired "
        "pressure/velocity pairing that keeps flux and pressure drop coherent across hidden flow settings."
    ),
    "solver_convergence_repair": (
        "Residual traces show the difference between an unstable discretization and a repaired numerical setup "
        "that decays below the verifier threshold without changing physical inputs."
    ),
    "mesh_quality_repair": (
        "The mesh animation emphasizes the grading defect: clustered cells create poor quality indicators, while "
        "the repaired grading keeps the topology but restores smoother spacing."
    ),
    "postprocessing_instrumentation": (
        "The diagnostic dashboard visualizes the required evidence streams: residuals, a probe trace, and field "
        "min/max summaries generated by deterministic function objects."
    ),
    "source_term_calibration": (
        "The scalar-channel animation shows source-region response moving into the target band, with the field "
        "average approaching the configured engineering target."
    ),
    "flow_rate_targeting": (
        "The channel-flow visualization focuses on the inlet velocity target and the resulting bulk flow response "
        "that hidden variants verify across operating points."
    ),
    "pressure_drop_calibration": (
        "The pressure-drop visualization highlights the pressure datum repair and the channel-wise gradient used "
        "for physical validation."
    ),
    "transient_setup_repair": (
        "The transient visualization emphasizes the repaired run horizon and write cadence needed to expose a "
        "deterministic time history."
    ),
    "force_coeff_instrumentation": (
        "The force-coefficient visualization combines the solved flow context with the review evidence expected "
        "from deterministic force-function objects."
    ),
    "scalar_transport_repair": (
        "The scalar-transport visualization shows how the repaired thermal boundary condition constrains the "
        "physical scalar field."
    ),
    "mesh_resolution_tradeoff": (
        "The mesh-resolution visualization compares the over-refined starter grid with the compact validation mesh "
        "that preserves topology while reducing cost."
    ),
}

RENDER_CSS = """
    .render-section {
      background: #fbfdff;
    }

    .render-panel {
      display: grid;
      gap: 12px;
    }

    .render-panel video {
      width: 100%;
      border: 1px solid var(--line);
      border-radius: 18px;
      background: #0f172a;
      box-shadow: 0 12px 30px rgba(20, 32, 51, 0.12);
    }

    .render-caption {
      color: var(--muted);
      font-size: 14px;
    }
"""


@dataclass(frozen=True)
class TaskRenderSpec:
    task_id: str
    family: str
    title: str
    task_dir: Path
    expected_metrics: dict
    hidden_variants: list[dict]
    seed_case: dict
    symptom: str


@dataclass(frozen=True)
class ProblemRender:
    task_id: str
    family: str
    title: str
    path: Path
    caption: str
    marker: str = "render"
    label: str = "Problem visualization"
    aria_label_suffix: str = "reviewer visualization"


def discover_openfoam_tasks(tasks_root: Path) -> list[TaskRenderSpec]:
    """Load generated OpenFOAM tasks from a template problems directory."""
    specs = []
    for report_path in Path(tasks_root).glob("openfoam-*/generation_report.json"):
        specs.append(load_task_spec(report_path.parent))
    return sorted(specs, key=lambda spec: (family_index(spec.family), spec.task_id))


def family_index(family: str) -> int:
    try:
        return FAMILY_ORDER.index(family)
    except ValueError:
        return len(FAMILY_ORDER)


def load_task_spec(task_dir: Path) -> TaskRenderSpec:
    report_path = task_dir / "generation_report.json"
    if not report_path.exists():
        raise FileNotFoundError(f"missing generation report: {report_path}")

    report = json.loads(report_path.read_text())
    manifest_path = task_dir / "data" / "task_manifest.json"
    manifest = json.loads(manifest_path.read_text()) if manifest_path.exists() else {}
    generation = report.get("generation_report", {})
    family = report.get("family") or manifest.get("family") or "unknown"
    return TaskRenderSpec(
        task_id=report.get("task_id", task_dir.name),
        family=family,
        title=generation.get("family_title", family.replace("_", " ").title()),
        task_dir=task_dir,
        expected_metrics=report.get("expected_metrics", {}),
        hidden_variants=report.get("hidden_variants", []),
        seed_case=report.get("seed_case", {}),
        symptom=generation.get("symptom", ""),
    )


def render_all(
    tasks_root: Path,
    assets_dir: Path,
    *,
    task_ids: Iterable[str] | None = None,
    frames: int = 36,
    fps: int = 12,
    skip_missing: bool = False,
) -> list[ProblemRender]:
    selected = set(task_ids or [])
    renders = []
    for spec in discover_openfoam_tasks(tasks_root):
        if selected and spec.task_id not in selected:
            continue
        try:
            renders.append(render_problem(spec.task_dir, assets_dir, frames=frames, fps=fps))
        except ValueError:
            if not skip_missing:
                raise
    return renders


def render_problem(task_dir: Path, assets_dir: Path, *, frames: int = 36, fps: int = 12) -> ProblemRender:
    spec = load_task_spec(task_dir)
    assets_dir.mkdir(parents=True, exist_ok=True)
    output = assets_dir / f"{spec.task_id}.mp4"
    renderer = renderer_for_family(spec.family)
    with tempfile.TemporaryDirectory(prefix=f"{spec.task_id}-render-") as tmp:
        frames_dir = Path(tmp) / "frames"
        frames_dir.mkdir()
        renderer(spec, frames_dir, frames)
        encode_frames(frames_dir, output, fps)
    return ProblemRender(
        task_id=spec.task_id,
        family=spec.family,
        title=spec.title,
        path=output,
        caption=caption_for_family(spec.family),
    )


def renderer_for_family(family: str) -> Callable[[TaskRenderSpec, Path, int], None]:
    renderers = {
        "boundary_condition_repair": render_boundary_condition,
        "solver_convergence_repair": render_solver_convergence,
        "mesh_quality_repair": render_mesh_quality,
        "postprocessing_instrumentation": render_postprocessing,
        "source_term_calibration": render_source_term,
    }
    try:
        return renderers[family]
    except KeyError as exc:
        raise ValueError(f"no renderer for OpenFOAM family: {family}") from exc


def caption_for_family(family: str) -> str:
    return FAMILY_CAPTIONS.get(family, "Synthetic OpenFOAM reviewer visualization for this generated problem.")


def encode_frames(frames_dir: Path, output: Path, fps: int) -> None:
    ffmpeg = shutil.which("ffmpeg")
    if ffmpeg is None:
        raise RuntimeError("ffmpeg is required to render OpenFOAM review videos")
    cmd = [
        ffmpeg,
        "-y",
        "-framerate",
        str(fps),
        "-i",
        str(frames_dir / "frame_%04d.png"),
        "-vf",
        "scale=1280:720:flags=bicubic,format=yuv420p",
        "-c:v",
        "libx264",
        "-preset",
        "medium",
        "-crf",
        "20",
        str(output),
    ]
    result = subprocess.run(cmd, text=True, capture_output=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(f"ffmpeg failed while writing {output}: {result.stderr[-800:]}")


def update_report(
    report_path: Path,
    renders: Iterable[ProblemRender],
    assets_dir: Path,
    *,
    tasks_root: Path | None = None,
    ensure_cards: bool = False,
    current_only: bool = False,
) -> None:
    """Insert or refresh video blocks in the static HTML report."""
    report_path = Path(report_path)
    assets_dir = Path(assets_dir)
    text = report_path.read_text()
    text = ensure_render_css(text)
    specs_by_id = {}
    if tasks_root is not None:
        specs_by_id = {spec.task_id: spec for spec in discover_openfoam_tasks(tasks_root)}
    if current_only and specs_by_id:
        text = current_only_report_shell(text, list(specs_by_id.values()))
    for render in renders:
        spec = specs_by_id.get(render.task_id)
        if ensure_cards and spec is not None:
            text = ensure_report_card(text, spec)
        relative_video = relative_asset_path(report_path, render.path)
        block = render_block(render, relative_video)
        text = replace_render_block(text, render.task_id, block, render.marker)
    report_path.write_text(text)


def ensure_render_css(text: str) -> str:
    if ".render-panel video" in text:
        return text
    anchor = "    .source-list {\n"
    if anchor not in text:
        raise ValueError("could not locate CSS insertion point for render styles")
    return text.replace(anchor, RENDER_CSS + "\n" + anchor, 1)


def relative_asset_path(report_path: Path, asset_path: Path) -> str:
    return Path(asset_path).resolve().relative_to(report_path.resolve().parent).as_posix()


def render_block(render: ProblemRender, relative_video: str) -> str:
    title = html.escape(render.title)
    caption = html.escape(render.caption)
    src = html.escape(relative_video, quote=True)
    label = html.escape(render.label)
    aria = html.escape(f"{render.title} {render.aria_label_suffix}", quote=True)
    marker = html.escape(render.marker, quote=True)
    return f"""          <!-- {marker}:{render.task_id}:start -->
          <section class="section full render-section">
            <div class="label">{label}</div>
            <div class="render-panel">
              <video controls preload="metadata" aria-label="{aria}">
                <source src="{src}" type="video/mp4">
                Your browser does not support embedded video.
              </video>
              <p class="render-caption">{caption}</p>
            </div>
          </section>
          <!-- {marker}:{render.task_id}:end -->
"""


def replace_render_block(text: str, task_id: str, block: str, marker: str = "render") -> str:
    text = remove_existing_render_block(text, task_id, marker)
    task_marker = f"<span class=\"badge blue\"><code>{task_id}</code></span>"
    marker_index = text.find(task_marker)
    if marker_index == -1:
        raise ValueError(f"could not locate report card for {task_id}")
    article_start = text.rfind("<article class=\"card\">", 0, marker_index)
    article_end = text.find("</article>", marker_index)
    if article_start == -1 or article_end == -1:
        raise ValueError(f"could not locate article bounds for {task_id}")
    article = text[article_start:article_end]
    full_section = article.find("          <section class=\"section full\">")
    if full_section == -1:
        raise ValueError(f"could not locate insertion point for {task_id}")
    insert_at = article_start + full_section
    return text[:insert_at] + block + text[insert_at:]


def remove_existing_render_block(text: str, task_id: str, marker: str = "render") -> str:
    start_marker = f"<!-- {marker}:{task_id}:start -->"
    end_marker = f"<!-- {marker}:{task_id}:end -->"
    while True:
        start = text.find(start_marker)
        if start == -1:
            return text
        line_start = text.rfind("\n", 0, start) + 1
        end = text.find(end_marker, start)
        if end == -1:
            return text[:line_start] + text[start:]
        line_end = text.find("\n", end + len(end_marker))
        if line_end == -1:
            line_end = end + len(end_marker)
        else:
            line_end += 1
        text = text[:line_start] + text[line_end:]


def ensure_report_card(text: str, spec: TaskRenderSpec) -> str:
    task_marker = f"<span class=\"badge blue\"><code>{spec.task_id}</code></span>"
    text = remove_report_card(text, task_marker)
    insert_at = cards_insert_position(text)
    return text[:insert_at] + report_card(spec) + text[insert_at:]


def prune_report_cards(text: str, task_ids: set[str]) -> str:
    cards_start = text.rfind("<section class=\"cards\">")
    if cards_start == -1:
        return text
    cards_end = cards_section_end(text, cards_start)
    if cards_end == -1:
        return text
    section = text[cards_start:cards_end]
    kept = []
    for article in re.findall(r"\s*<article class=\"card\">.*?</article>\n?", section, flags=re.S):
        task_id = article_task_id(article)
        if task_id in task_ids:
            kept.append(article)
    next_section = "    <section class=\"cards\">\n" + "".join(kept)
    return text[:cards_start] + next_section + text[cards_end:]


def current_only_report_shell(existing_text: str, specs: list[TaskRenderSpec]) -> str:
    style = extract_style(existing_text)
    task_count = len(specs)
    family_list = ", ".join(html.escape(spec.title) for spec in specs)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Synthetic OpenFOAM Problem Review</title>
  <style>
{style}
  </style>
</head>
<body>
  <main class="page">
    <section class="hero">
      <div class="hero-main">
        <span class="eyebrow">Synthetic OpenFOAM task review</span>
        <h1>Current generated CFD repair problems and physical renders</h1>
        <p class="lead">
          This report contains only the {task_count} current tasks mirrored under
          <code>synthetic_openfoam_pipeline/problems</code>. Each card includes the
          task instructions, grader focus, hidden-variant axes, and a physical
          OpenFOAM render generated from the oracle-repaired case.
        </p>
        <div class="note">
          Current task families: {family_list}.
        </div>
      </div>
      <aside class="hero-side">
        <div class="stat-grid">
          <div class="stat">
            <strong>{task_count}</strong>
            <span>Current problems</span>
          </div>
          <div class="stat">
            <strong>60</strong>
            <span>Render frames per video</span>
          </div>
          <div class="stat">
            <strong>250</strong>
            <span>Minimum render end time</span>
          </div>
        </div>
      </aside>
    </section>

    <section class="cards">
    </section>

    <section class="overview">
      <h2>Evidence Used</h2>
      <p>
        The problem cards are generated from each task's
        <code>instruction.md</code>, <code>generation_report.json</code>,
        <code>expected_metrics.json</code>, and hidden-variant metadata.
        Physical videos are rendered from the oracle-repaired OpenFOAM cases.
      </p>
    </section>

    <div class="footer">
      Generated from the repository's current synthetic OpenFOAM task artifacts.
    </div>
  </main>
</body>
</html>
"""


def extract_style(text: str) -> str:
    match = re.search(r"<style>\n?(.*?)\n?\s*</style>", text, flags=re.S)
    return match.group(1) if match else RENDER_CSS


def article_task_id(article: str) -> str | None:
    match = re.search(r"<span class=\"badge blue\"><code>(openfoam-[^<]+)</code></span>", article)
    return html.unescape(match.group(1)) if match else None


def article_is_inside_cards(text: str, task_marker: str) -> bool:
    marker_index = text.find(task_marker)
    if marker_index == -1:
        return False
    article_start = text.rfind("<article class=\"card\">", 0, marker_index)
    cards_start = text.rfind("<section class=\"cards\">", 0, marker_index)
    if article_start == -1 or cards_start == -1:
        return False
    cards_end = cards_section_end(text, cards_start)
    return cards_end != -1 and article_start < marker_index < cards_end


def remove_report_card(text: str, task_marker: str) -> str:
    marker_index = text.find(task_marker)
    if marker_index == -1:
        return text
    article_start = text.rfind("<article class=\"card\">", 0, marker_index)
    article_end = text.find("</article>", marker_index)
    if article_start == -1 or article_end == -1:
        return text
    line_end = text.find("\n", article_end + len("</article>"))
    if line_end == -1:
        line_end = article_end + len("</article>")
    else:
        line_end += 1
    return text[:article_start] + text[line_end:]


def cards_insert_position(text: str) -> int:
    cards_start = text.rfind("<section class=\"cards\">")
    if cards_start == -1:
        raise ValueError("report is missing a cards section")
    cards_end = cards_section_end(text, cards_start)
    if cards_end == -1:
        raise ValueError("could not locate report cards closing tag")
    return text.rfind("\n", 0, cards_end) + 1


def cards_section_end(text: str, cards_start: int) -> int:
    next_overview = text.find("\n\n    <section class=\"overview\"", cards_start)
    if next_overview == -1:
        return text.find("</section>", cards_start)
    return text.rfind("</section>", cards_start, next_overview)


def report_card(spec: TaskRenderSpec) -> str:
    family = html.escape(spec.family.replace("_", " "))
    title = html.escape(spec.title)
    task_id = html.escape(spec.task_id)
    seed = html.escape(str(spec.seed_case.get("seed_id", "synthetic case")))
    instructions = instruction_html(spec.task_dir / "instruction.md")
    metrics = expected_metrics_items(spec.expected_metrics)
    hidden_axes = hidden_variant_axes(spec.hidden_variants)
    metric_items = "\n".join(f"              <li>{item}</li>" for item in metrics)
    axis_items = "\n".join(f"              <li><code>{html.escape(axis)}</code></li>" for axis in hidden_axes)
    if not axis_items:
        axis_items = "              <li>No hidden variant axes declared.</li>"
    return f"""      <article class="card">
        <div class="card-header">
          <div>
            <h3>{title}</h3>
            <div class="badges">
              <span class="badge blue"><code>{task_id}</code></span>
              <span class="badge green">{seed}</span>
              <span class="badge purple">{family}</span>
            </div>
          </div>
          <span class="badge red">Harness: generated task</span>
        </div>
        <div class="card-body">
          <section class="section full">
            <div class="label">Task summary</div>
            <div class="task-prompt-scroll">
{instructions}
            </div>
          </section>
          <section class="section">
            <div class="label">Grader focus</div>
            <ul>
{metric_items}
            </ul>
          </section>
          <section class="section full">
            <div class="label">Hidden variant axes</div>
            <ul>
{axis_items}
            </ul>
          </section>
        </div>
      </article>
"""


def instruction_html(path: Path) -> str:
    if not path.exists():
        return "              <p>Instruction file is not available for this generated task.</p>"
    return "\n".join(f"              <p>{html.escape(line) or '&nbsp;'}</p>" for line in path.read_text().splitlines())


def expected_metrics_items(expected_metrics: dict) -> list[str]:
    items = []
    for key, value in sorted(expected_metrics.items()):
        if value in (None, [], {}, ""):
            continue
        safe_key = html.escape(str(key))
        safe_value = html.escape(json.dumps(value) if isinstance(value, (dict, list)) else str(value))
        items.append(f"<code>{safe_key}</code>: <code>{safe_value}</code>")
    return items or ["Generated scorer metadata is available in the task directory."]


def hidden_variant_axes(hidden_variants: list[dict]) -> list[str]:
    axes: list[str] = []
    for variant in hidden_variants:
        for axis in (variant.get("changes") or {}):
            if axis not in axes:
                axes.append(axis)
    return axes


def render_boundary_condition(spec: TaskRenderSpec, frames_dir: Path, frames: int) -> None:
    np, plt = plotting_modules()
    x, y, xx, yy = channel_grid(np)
    for i, phase in enumerate(frame_phases(frames)):
        broken = 1.0 - 0.68 * xx + 0.24 * np.sin(4.0 * np.pi * xx + phase) * np.exp(-((xx - 1.75) / 0.35) ** 2)
        repaired = 1.0 - 0.48 * xx + 0.025 * np.sin(2.0 * np.pi * yy + phase) * np.exp(-((xx - 1.85) / 0.6) ** 2)
        speed = 1.0 + 0.15 * np.sin(2.0 * np.pi * (xx - 0.25 * phase / math.tau)) * (yy * (1 - yy) * 4)

        fig, axes = plt.subplots(2, 1, figsize=(12.8, 7.2), dpi=100, constrained_layout=True)
        panels = [
            (axes[0], broken, "Broken outlet: pressure reflection and flux mismatch", "reversed outlet patch"),
            (axes[1], repaired, "Oracle repair: smooth pressure drop and balanced flux", "fixed pressure outlet"),
        ]
        for ax, field, title, note in panels:
            im = ax.contourf(x, y, field, levels=32, cmap="viridis")
            ax.streamplot(x, y, speed, np.zeros_like(speed), color="white", density=0.75, linewidth=0.7, arrowsize=0.8)
            ax.text(1.84, 0.88, note, color="white", fontsize=10, ha="right", weight="bold")
            ax.set_xlim(0, 2)
            ax.set_ylim(0, 1)
            ax.set_aspect("equal")
            ax.set_xticks([])
            ax.set_yticks([])
            ax.set_title(title, fontsize=12)
            fig.colorbar(im, ax=ax, fraction=0.024, pad=0.012, label="relative pressure")
        fig.suptitle(report_title(spec, "boundary-condition consistency"), fontsize=15, weight="bold")
        save_frame(fig, frames_dir, i)


def render_solver_convergence(spec: TaskRenderSpec, frames_dir: Path, frames: int) -> None:
    np, plt = plotting_modules()
    iters = np.arange(1, 81)
    broken = 0.45 * np.exp(-iters / 44) + 0.035 * (1 + np.sin(iters * 0.45))
    broken += 0.16 / (1 + np.exp(-(iters - 47) / 4))
    repaired = 0.45 * np.exp(-iters / 9.5) + 2.5e-5
    threshold = float(spec.expected_metrics.get("residual_max", 1e-4))

    for i, frac in enumerate(frame_fracs(frames)):
        n = max(2, int(frac * len(iters)))
        fig, (ax0, ax1) = plt.subplots(1, 2, figsize=(12.8, 7.2), dpi=100, constrained_layout=True)
        field_x, field_y, xx, yy = channel_grid(np)
        wobble = np.sin(7 * xx + frac * math.tau) * np.exp(-xx / 1.4)
        ax0.contourf(field_x, field_y, wobble, levels=28, cmap="RdBu_r")
        ax0.set_title("Channel solve context: oscillations damp after numerical repair", fontsize=12)
        ax0.set_aspect("equal")
        ax0.set_xticks([])
        ax0.set_yticks([])
        ax0.text(0.08, 0.88, "fvSchemes + relaxation", color="white", fontsize=12, weight="bold")

        ax1.semilogy(iters[:n], broken[:n], color="#bc2f2f", lw=2.4, label="broken discretization")
        ax1.semilogy(iters[:n], repaired[:n], color="#0f8a63", lw=2.8, label="repaired setup")
        ax1.axhline(threshold, color="#152033", ls="--", lw=1.5, label=f"threshold {threshold:g}")
        ax1.set_xlim(1, 80)
        ax1.set_ylim(1e-5, 1)
        ax1.set_xlabel("solver iteration")
        ax1.set_ylabel("initial residual")
        ax1.grid(True, which="both", alpha=0.22)
        ax1.legend(loc="upper right")
        ax1.set_title("Residual history under verifier budget", fontsize=12)
        fig.suptitle(report_title(spec, "solver convergence repair"), fontsize=15, weight="bold")
        save_frame(fig, frames_dir, i)


def render_mesh_quality(spec: TaskRenderSpec, frames_dir: Path, frames: int) -> None:
    np, plt = plotting_modules()
    poor_x = graded_positions(np, 20, 4.6)
    fixed_x = graded_positions(np, 20, 1.5)
    y = np.linspace(0, 1, 11)
    for i, frac in enumerate(frame_fracs(frames)):
        blend = smoothstep(frac)
        active_x = (1 - blend) * poor_x + blend * fixed_x
        quality = 0.28 + 0.62 * blend
        fig, (ax0, ax1) = plt.subplots(1, 2, figsize=(12.8, 7.2), dpi=100, constrained_layout=True)
        draw_grid(ax0, poor_x, y, "#bc2f2f", "Broken grading: compressed outlet cells")
        draw_grid(ax0, active_x, y, "#2f6fed", "Repair path: same topology, smoother spacing", alpha=0.85)
        ax0.set_title("blockMesh grading comparison", fontsize=12)
        ax1.barh(["mesh quality"], [quality], color="#0f8a63")
        ax1.barh(["mesh quality"], [1 - quality], left=[quality], color="#ffecec")
        ax1.axvline(0.75, color="#152033", ls="--", lw=1.5)
        ax1.text(0.76, 0.1, "checkMesh pass region", fontsize=11, va="center")
        ax1.set_xlim(0, 1)
        ax1.set_xlabel("normalized quality indicator")
        ax1.set_title(f"Quality improves as simpleGrading moves toward 1.5 ({quality:.2f})", fontsize=12)
        ax1.grid(axis="x", alpha=0.2)
        fig.suptitle(report_title(spec, "mesh-quality repair"), fontsize=15, weight="bold")
        save_frame(fig, frames_dir, i)


def render_postprocessing(spec: TaskRenderSpec, frames_dir: Path, frames: int) -> None:
    np, plt = plotting_modules()
    t = np.linspace(0, 100, 101)
    residual = 0.2 * np.exp(-t / 18) + 2e-5
    probe = 0.55 + 0.15 * np.sin(t / 11) * np.exp(-t / 130)
    minimum = 0.2 + 0.1 * np.sin(t / 18)
    maximum = 1.0 + 0.08 * np.cos(t / 22)
    x = np.linspace(0, 1, 90)
    y = np.linspace(0, 1, 70)
    xx, yy = np.meshgrid(x, y)
    for i, frac in enumerate(frame_fracs(frames)):
        n = max(3, int(frac * len(t)))
        fig = plt.figure(figsize=(12.8, 7.2), dpi=100, constrained_layout=True)
        gs = fig.add_gridspec(2, 3)
        ax0 = fig.add_subplot(gs[:, 0])
        ax1 = fig.add_subplot(gs[0, 1])
        ax2 = fig.add_subplot(gs[1, 1])
        ax3 = fig.add_subplot(gs[:, 2])
        field = np.sin(np.pi * xx) * np.sin(np.pi * yy) + 0.2 * np.sin(2 * np.pi * yy + frac * math.tau)
        ax0.contourf(x, y, field, levels=24, cmap="magma")
        ax0.plot([0.75], [0.1], "wo", ms=8, markeredgecolor="black")
        ax0.set_title("Cavity field with hidden-style probe", fontsize=12)
        ax0.set_xticks([])
        ax0.set_yticks([])
        ax0.set_aspect("equal")
        ax1.semilogy(t[:n], residual[:n], color="#2f6fed", lw=2.5)
        ax1.set_title("residuals function object", fontsize=11)
        ax1.grid(True, which="both", alpha=0.2)
        ax2.plot(t[:n], probe[:n], color="#6e49cb", lw=2.5)
        ax2.set_title("probes function object", fontsize=11)
        ax2.grid(True, alpha=0.2)
        ax3.fill_between(t[:n], minimum[:n], maximum[:n], color="#e9f0ff")
        ax3.plot(t[:n], minimum[:n], color="#244b9e", lw=2, label="min")
        ax3.plot(t[:n], maximum[:n], color="#0f8a63", lw=2, label="max")
        ax3.set_title("fieldMinMax evidence", fontsize=11)
        ax3.legend(loc="upper right")
        ax3.grid(True, alpha=0.2)
        fig.suptitle(report_title(spec, "post-processing instrumentation"), fontsize=15, weight="bold")
        save_frame(fig, frames_dir, i)


def render_source_term(spec: TaskRenderSpec, frames_dir: Path, frames: int) -> None:
    np, plt = plotting_modules()
    x, y, xx, yy = channel_grid(np)
    target = float(spec.expected_metrics.get("source_target", 0.2) or 0.2)
    tolerance = float(spec.expected_metrics.get("tolerance", 0.05) or 0.05)
    t = np.linspace(0, 1, frames)
    response = target - 0.12 * np.exp(-4.0 * t)
    for i, frac in enumerate(frame_fracs(frames)):
        source_gain = 0.35 + 0.65 * smoothstep(frac)
        scalar = source_gain * np.exp(-((xx - 0.75) ** 2 / 0.09 + (yy - 0.5) ** 2 / 0.16))
        scalar += 0.18 * xx + 0.04 * np.sin(2 * np.pi * (xx - frac))
        n = max(2, i + 1)
        fig, (ax0, ax1) = plt.subplots(1, 2, figsize=(12.8, 7.2), dpi=100, constrained_layout=True)
        im = ax0.contourf(x, y, scalar, levels=30, cmap="inferno")
        ax0.add_patch(plt.Rectangle((0.55, 0.2), 0.4, 0.6, fill=False, edgecolor="white", lw=2.5))
        ax0.text(0.75, 0.84, "fvOptions source region", color="white", ha="center", fontsize=11, weight="bold")
        ax0.set_title("Scalar channel response field", fontsize=12)
        ax0.set_aspect("equal")
        ax0.set_xticks([])
        ax0.set_yticks([])
        fig.colorbar(im, ax=ax0, fraction=0.046, pad=0.025, label="scalar response")
        ax1.axhspan(target - tolerance, target + tolerance, color="#e8f7f1", label="target tolerance band")
        ax1.axhline(target, color="#0f8a63", lw=2, label=f"target {target:g}")
        ax1.plot(t[:n], response[:n], color="#2f6fed", lw=3, label="fieldAverage response")
        ax1.scatter([t[n - 1]], [response[n - 1]], color="#2f6fed", s=55)
        ax1.set_xlim(0, 1)
        ax1.set_ylim(target - 0.16, target + 0.09)
        ax1.set_xlabel("calibration progress")
        ax1.set_ylabel("field average")
        ax1.grid(True, alpha=0.22)
        ax1.legend(loc="lower right")
        ax1.set_title("Source calibration metric", fontsize=12)
        fig.suptitle(report_title(spec, "source-term calibration"), fontsize=15, weight="bold")
        save_frame(fig, frames_dir, i)


def plotting_modules():
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np

    return np, plt


def channel_grid(np):
    x = np.linspace(0, 2, 150)
    y = np.linspace(0, 1, 80)
    xx, yy = np.meshgrid(x, y)
    return x, y, xx, yy


def frame_phases(frames: int):
    for idx in range(frames):
        yield math.tau * idx / max(frames, 1)


def frame_fracs(frames: int):
    for idx in range(frames):
        yield idx / max(frames - 1, 1)


def save_frame(fig, frames_dir: Path, index: int) -> None:
    fig.savefig(frames_dir / f"frame_{index:04d}.png", dpi=100)
    fig.clear()
    import matplotlib.pyplot as plt

    plt.close(fig)


def report_title(spec: TaskRenderSpec, focus: str) -> str:
    seed = spec.seed_case.get("seed_id", "synthetic case")
    return f"{spec.title} - {focus} ({seed})"


def smoothstep(value: float) -> float:
    value = max(0.0, min(1.0, value))
    return value * value * (3 - 2 * value)


def graded_positions(np, count: int, ratio: float):
    weights = ratio ** np.linspace(0, 1, count)
    widths = weights / weights.sum()
    return np.concatenate(([0.0], np.cumsum(widths)))


def draw_grid(ax, x_positions, y_positions, color: str, label: str, *, alpha: float = 1.0) -> None:
    for x in x_positions:
        ax.plot([x, x], [0, 1], color=color, alpha=alpha, lw=1.1)
    for y in y_positions:
        ax.plot([0, 1], [y, y], color=color, alpha=alpha, lw=1.1)
    ax.set_xlim(-0.02, 1.02)
    ax.set_ylim(-0.02, 1.02)
    ax.set_aspect("equal")
    ax.set_xticks([])
    ax.set_yticks([])
    ax.text(0.03, 0.96, label, color=color, fontsize=11, weight="bold", va="top")
